name: Approve pull requests securely
description: Approve pull requests securely
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: green
inputs:
  app_id:
    description: |
      GitHub App ID
    required: true
  app_private_key:
    description: |
      GitHub App Private Key
    required: true
  server_repository_name:
    description: |
      Server repository name
    required: true
  pull_request_number:
    description: |
      The pull request number of the updated pull request
    required: true

  github_token:
    description: |
      GitHub token to read the pull request.
      `contents: read` and `pull_requests:read` permissions are required.
    required: false
    default: ${{ github.token }}
  repository_name:
    description: |
      The repository name of the updated pull request
    required: false
    default: ${{ github.event.repository.name }}
  repository_owner:
    description: |
      The repository owner of the updated pull request
    required: false
    default: ${{ github.repository_owner }}
  server_repository_owner:
    description: |
      A server repository owner.
    required: false
    default: ${{ github.repository_owner }}
  allowed_committers:
    description: |
      A list of allowed committers.
    required: false
    default: |
      renovate[bot]
      dependabot[bot]
runs:
  using: composite
  steps:
    - uses: csm-actions/core-approve-pr-action/validate@2bfb2a4f082938741ac6b722e3d2e6e9436c2803 # v0.0.2
      id: validate
      with:
        github_token: ${{ inputs.github_token }}
        pull_request_number: ${{ inputs.pull_request_number }}
        repository_owner: ${{ inputs.repository_owner }}
        repository_name: ${{ inputs.repository_name }}
        allowed_committers: ${{ inputs.allowed_committers }}

    # Create a GitHub App token to create and delete a label
    - uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
      if: steps.validate.outputs.approved == 'true'
      id: token
      with:
        app-id: ${{inputs.app_id}}
        private-key: ${{inputs.app_private_key}}
        permission-issues: write
        owner: ${{ github.server_repository_owner }}
        repositories: |
          ${{inputs.server_repository_name}}

    - uses: csm-actions/label-action@e882c05058dd13a9072a60980f490728cea7de1c # v0.1.0
      if: steps.validate.outputs.approved == 'true'
      with:
        prefix: approve-pr-
        description: ${{inputs.repository_owner}}/${{inputs.repository_name}}/${{inputs.pull_request_number}}
        repository_owner: ${{inputs.server_repository_owner}}
        repository_name: ${{inputs.server_repository_name}}
        github_token: ${{steps.token.outputs.token}}
