name: Approve pull requests securely
description: Approve pull requests securely
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: green
inputs:
  app_id:
    description: |
      GitHub App ID
    required: true
  app_private_key:
    description: |
      GitHub App Private Key
    required: true

  # For Client
  server_repository_name:
    description: |
      Server repository name.
      Required for client mode.
    required: false
  server_repository_owner:
    description: |
      Server repository owner.
    required: false
    default: ${{github.repository_owner}}
  repository_owner:
    description: |
      The repository owner of the pull request to approve.
    required: false
    default: ${{github.repository_owner}}
  repository_name:
    description: |
      The repository name of the pull request to approve.
    required: false
    default: ${{github.event.repository.name}}
  pull_request_number:
    description: |
      The pull request number to approve.
      Required for client mode.
    required: false

  # For both Client and Server
  github_token:
    description: |
      GitHub token.
      For client: used to read the pull request (`contents:read` and `pull_requests:read` permissions required).
      For server: used to approve the pull request (`pull_requests:write` permission required).
    required: false
    default: ${{github.token}}
  allowed_committers:
    description: |
      A list of allowed committers.
    required: false
    default: |
      renovate[bot]
      dependabot[bot]
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/index.js"
