name: Approve Pull Requests
description: Approve Pull Requests
inputs:
  allowed_committers:
    description: |
      A list of allowed committers.
    required: false
    default: |
      renovate[bot]
      dependabot[bot]
  github_token:
    description: |
      GitHub Access token to approve pull requests.
      `pull_requests:write` permission is required.
    required: true
runs:
  using: composite
  steps:
    # Approve the pull request
    - shell: bash
      if: steps.validate.outputs.valid == 'true'
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ steps.info.outputs.repo_full_name }}
        NUMBER: ${{ steps.info.outputs.pr_number }}
        SHA: ${{ steps.validate.outputs.last_sha }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/$REPO/pulls/$NUMBER/reviews" \
          -f "commit_id=$SHA" \
          -f "event=APPROVE"

    # Create a pull request comment to report an error
    - if: failure()
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ steps.info.outputs.repo_full_name }}
        NUMBER: ${{ steps.info.outputs.pr_number }}
        COMMENT: |
          ## :x: Failed to approve this pull request

          [Workflow](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
      run: |
        gh pr comment \
          -R "$REPO" \
          -b "${COMMENT}" \
          "$NUMBER"
