name: Approve Pull Requests
description: Approve Pull Requests
inputs:
  github_token:
    description: |
      GitHub Access token to approve pull requests.
      `pull_requests:write` permission is required.
    required: true
  pull_request_number:
    description: |
      A pull request number.
    required: true
  sha:
    description: |
      An approved commit SHA.
    required: true

  repository_owner:
    description: |
      A GitHub repository owner.
    required: false
    default: ${{ github.repository_owner }}
  repository_name:
    description: |
      A GitHub repository name.
    required: false
    default: ${{ github.event.repository.name }}
runs:
  using: composite
  steps:
    # Approve the pull request
    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ inputs.repository_owner }}/${{ inputs.repository_name }}
        NUMBER: ${{ inputs.pull_request_number }}
        SHA: ${{ inputs.sha }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/$REPO/pulls/$NUMBER/reviews" \
          -f "commit_id=$SHA" \
          -f "event=APPROVE"

    # Create a pull request comment to report an error
    - if: failure()
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ inputs.repository_owner }}/${{ inputs.repository_name }}
        NUMBER: ${{ inputs.pull_request_number }}
        COMMENT: |
          ## :x: Failed to approve this pull request

          [Workflow](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
      run: |
        gh pr comment \
          -R "$REPO" \
          -b "${COMMENT}" \
          "$NUMBER"
