name: Approve Pull Requests
description: Approve Pull Requests
inputs:
  github_token:
    description: |
      GitHub Access token to approve pull requests.
      `pull_requests:write` permission is required.
    required: true
  app_id:
    description: |
      GitHub App ID.
      Permissions `pull_requests:read` and `contents:read` are required to validate pull requests.
    required: true
  app_private_key:
    description: |
      GitHub App Private Key
    required: true
runs:
  using: composite
  steps:
    - id: pr
      shell: bash
      env:
        # ${repo}/${pull_request_number}
        LABEL_DESCRIPTION: ${{ github.event.label.description }}
      run: |
        repo_full_name=${LABEL_DESCRIPTION%/*}
        {
          echo "repository_owner=${repo_full_name%/*}"
          echo "repository_name=${repo_full_name#*/}"
          echo "pull_request_number=${LABEL_DESCRIPTION##*/}"
        } >> "$GITHUB_OUTPUT"

    - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
      if: steps.validate.outputs.approved == 'true'
      id: token
      with:
        app-id: ${{inputs.app_id}}
        private-key: ${{inputs.app_private_key}}
        permission-pull-requests: read
        permission-contents: read
        owner: ${{ steps.pr.outputs.repository_owner }}
        repositories: |
          ${{steps.pr.outputs.repository_name}}

    - uses: securefix-action/core-approve-pr-action/validate@26dd9ec571549a434c2731644bdbb495b688816c # v0.0.1
      id: validate
      with:
        github_token: ${{ steps.token.outputs.token }}
        pull_request_number: ${{ steps.pr.outputs.pull_request_number }}
        repository_owner: ${{ steps.pr.outputs.repository_owner }}
        repository_name: ${{ steps.pr.outputs.repository_name }}

    - if: steps.validate.outputs.approved == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ steps.pr.outputs.repository_owner }}/${{ steps.pr.outputs.repository_name }}
        NUMBER: ${{ steps.pr.outputs.pull_request_number }}
        SHA: ${{ steps.validate.outputs.approved_sha }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/$REPO/pulls/$NUMBER/reviews" \
          -f "commit_id=$SHA" \
          -f "event=APPROVE"

    # Create a pull request comment to report an error
    - if: failure()
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ steps.pr.outputs.repository_owner }}/${{ steps.pr.outputs.repository_name }}
        NUMBER: ${{ steps.pr.outputs.pull_request_number }}
        COMMENT: |
          ## :x: Failed to approve this pull request

          [Workflow](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
      run: |
        gh pr comment \
          -R "$REPO" \
          -b "${COMMENT}" \
          "$NUMBER"
