name: Approve Pull Requests
description: Approve Pull Requests
inputs:
  github_token:
    description: |
      GitHub Access token to approve pull requests.
      `pull_requests:write` permission is required.
    required: true
  pull_request_number:
    description: |
      A pull request number.
    required: true
  sha:
    description: |
      An approved commit SHA.
    required: true

  repository_owner:
    description: |
      A GitHub repository owner.
    required: false
    default: ${{ github.repository_owner }}
  repository_name:
    description: |
      A GitHub repository name.
    required: false
    default: ${{ github.event.repository.name }}
runs:
  using: composite
  steps:
    - id: pr
      shell: bash
      env:
        # ${repo}/${pull_request_number}
        LABEL_DESCRIPTION: ${{ github.event.label.description }}
      run: |
        repo_full_name=${LABEL_DESCRIPTION%/*}
        {
          echo "repo_owner=${repo_full_name%/*}"
          echo "repo_name=${repo_full_name#*/}"
          echo "pr_number=${LABEL_DESCRIPTION##*/}"
        } >> "$GITHUB_OUTPUT"

    - uses: securefix-action/core-approve-pr-action/validate@main
      id: validate
      with:
        github_token: ${{ inputs.github_token }}
        pull_request_number: ${{ steps.pr.outputs.pull_request_number }}
        repository_owner: ${{ steps.pr.outputs.repository_owner }}
        repository_name: ${{ steps.pr.outputs.repository_name }}

    - if: steps.validate.outputs.approved == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ steps.pr.outputs.repository_owner }}/${{ steps.pr.outputs.repository_name }}
        NUMBER: ${{ steps.pr.outputs.pull_request_number }}
        SHA: ${{ steps.validate.outputs.approved_sha }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/$REPO/pulls/$NUMBER/reviews" \
          -f "commit_id=$SHA" \
          -f "event=APPROVE"

    # Create a pull request comment to report an error
    - if: failure()
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ steps.pr.outputs.repository_owner }}/${{ steps.pr.outputs.repository_name }}
        NUMBER: ${{ steps.pr.outputs.pull_request_number }}
        COMMENT: |
          ## :x: Failed to approve this pull request

          [Workflow](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
      run: |
        gh pr comment \
          -R "$REPO" \
          -b "${COMMENT}" \
          "$NUMBER"
