name: Parse a label
description: Parse a label
outputs:
  repository_owner:
    description: |
      The repository owner of the approved pull request
    value: ${{ steps.info.outputs.repo_owner }}
  repository_name:
    description: |
      The repository name of the approved pull request
    value: ${{ steps.info.outputs.repo_name }}
  pull_request_number:
    description: |
      The pull request number of the approved pull request
    value: ${{ steps.info.outputs.pr_number }}
runs:
  using: composite
  steps:
    - id: info
      shell: bash
      env:
        # ${repo}/${pull_request_number}
        LABEL_DESCRIPTION: ${{ github.event.label.description }}
      run: |
        repo_full_name=${LABEL_DESCRIPTION%/*}
        {
          echo "repo_owner=${repo_full_name%/*}"
          echo "repo_name=${repo_full_name#*/}"
          echo "pr_number=${LABEL_DESCRIPTION##*/}"
        } >> "$GITHUB_OUTPUT"
